### ISSUE TITLE
gssr 아지트

### ISSUE THREAD

**Issue by bohyunjung** [gssr-blog/gssr-blog.github.io#5]
# 공간 후보 답사
## 1안
* 경기도 성남시 분당구 불정로77번길 4-7 http://naver.me/GYdnFc5o
![s__18472970](https://user-images.githubusercontent.com/8598722/29348091-0a4d0290-828c-11e7-91e9-5ac0f7a8924d.jpg)
* 탁구장으로 쓰이던 공간
* 공기 순환 창문이 몇 개 있으나, 최근 비가 들이닥침
* 주인이 곧 페인트칠을 새로 할 예정이라 하니, 커스텀화 할 여지는 많지 않을 지도
* 1000 / 60
* 고상우: 뒤틀린 차원의 종이인간
## 2안
* 경기도 성남시 분당구 불정로77번길 3 http://naver.me/FcE0Kmhp
![s__18472972](https://user-images.githubusercontent.com/8598722/29348088-084aaed4-828c-11e7-8924-aa95de831c26.jpg)
* 세 놓은 적 없는 공간
* 공간 자체는 1안보다 아기자기해보이며 커스텀화 할 여지가 많아보임
* 전력공급판넬(?)은 1안보다 많음
* 공기 질은 1안보다 살짝 떨어지기도 하는 듯
* 1000 / 60

# 운영 관련
## 평일 낮 시간에 공간을 놀려야 할까?

**Comment by bohyunjung** [comment]
## 도어락 개소리
* 암구호 시스템: 수하 시 응답 없을 경우 굉음 재생

**Comment by bohyunjung** [comment]
## 꾸미기 아이디어
* [레터링박스](https://www.coupang.com/vp/products/26799609?itemId=103692917&vendorItemId=3197450880&q=%EB%A0%88%ED%84%B0%EB%A7%81%EB%B0%95%EC%8A%A4&itemsCount=36&searchId=fb9bab71d5824384b651fbe0ccaa1aa1&rank=0) 놓고싶다
* [달모양 램프](http://storefarm.naver.com/pcbox/products/609860966?n_media=27758&n_query=%EB%8B%AC%EB%9E%A8%ED%94%84&n_rank=1&n_ad_group=grp-a001-02-000000002259046&n_ad=nad-a001-02-000000010702478&n_campaign_type=2&n_mall_pid=609860966&NaPm=ct%3Dj6elxhu0%7Cci%3D0yu00015RTbnlOldxeLc%7Ctr%3Dpla%7Chk%3Ddb96e1c1c7e944251610c5743626c172afa6f804) 이것도

**Comment by sangwoo108** [comment]
asana 이관
